name: "CI/CD"
on:
  push:
    tags:
      - 'v*.*.*'
  #  branches: ["main"]
  # pull_request:
  #   branches: ["main"]

jobs:
  check-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'
        command: |
          echo $ {{ steps.version.outputs.is_valid }}
    outputs:
      version-valid: $ {{ steps.version.outputs.is_valid }}

  buildDocker:
    needs: check-tag
    if: ${{ needs.check-tag.outputs.version-valid == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run build on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_SECRET_KEY}}
          command: |
            cd ${{ secrets.WORK_DIR }};
            git checkout main;
            git pull;
            echo "TAG " ${{ github.ref_name }};
            sudo docker login;
            sudo docker build -t mikhailpastushenko/testchessanalyzer:${{ github.ref_name }} . ;
            sudo docker push mikhailpastushenko/testchessanalyzer:${{ github.ref_name }};
                    
  deploy:
    needs: buildDocker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run build on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_SECRET_KEY}}
          command: |
            cd ${{ secrets.QBEC_DIR }};
            sudo qbec apply default --vm:ext-str image_tag=${{ github.ref_name }} --yes ;

