name: "CI/CD"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  buildDocker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run build on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_SECRET_KEY}}
          command: |
            cd ${{ secrets.WORK_DIR }};
            git checkout main;
            git pull;
            # sudo dockerlogin -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_PASS}};
            # sudo docker build -t mikhailpastushenko/testchessanalyzer:latest;
            # sudo docker push -t mikhailpastushenko/testchessanalyzer:latest;
            
            
#  deploy:
#    needs: buildDocker
#    runs-on: ubuntu-latest
#    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      
      # - name: Run build on remote server
      #   uses: D3rHase/ssh-command-action@v0.2.2
      #   with:
      #     host: ${{secrets.SSH_HOST}}
      #     user: ${{secrets.SSH_USER}}
      #     private_key: ${{secrets.SSH_PRIVATE_KEY}}
      #     command: |
      #       cd ${{ secrets.PROJECT_FOLDER }};
      #       git checkout main;
      #       git pull;
